export const languages = [
  { name: "HTML", image: "/assets/skills/html5.svg" },
  { name: "CSS", image: "/assets/skills/css3.svg" },
  { name: "Javascript", image: "/assets/skills/javascript.svg" },
  // { name: "Dart", image: "/assets/skills/dart.svg" },
  { name: "Java", image: "/assets/skills/java.svg" },
  { name: "Typescript", image: "/assets/skills/typescript.svg" },
  { name: "ReactJs", image: "/assets/skills/react.svg" },
  { name: "NextJs", image: "/assets/skills/nextdotjs.svg" },
  // { name: "Flutter", image: "/assets/skills/flutter.svg" },
  { name: "Tailwind CSS", image: "/assets/skills/tailwindcss.svg" },
  { name: "Bootstrap", image: "/assets/skills/bootstrap.svg" },
  { name: "Redux", image: "/assets/skills/redux.svg" },
  { name: "GSAP", image: "/assets/skills/gsap.svg" },
  { name: "Framer Motion", image: "/assets/skills/framer-motion.svg" },
  { name: "NodeJs", image: "/assets/skills/nodedotjs.svg" },
  { name: "Springboot", image: "/assets/skills/spring.svg" },
  { name: "Express", image: "/assets/skills/express.svg" },
  { name: "MongoDB", image: "/assets/skills/mongodb.svg" },
  { name: "Python", image: "/assets/skills/python.svg" },
  { name: "Firebase", image: "/assets/skills/firebase.svg" },
  { name: "Redis", image: "/assets/skills/redis.svg" },
  { name: "PostgreSQL", image: "/assets/skills/postgresql.svg" },
  { name: "Prisma", image: "/assets/skills/prisma.svg" },
  { name: "Git", image: "/assets/skills/git.svg" },
  { name: "Jira", image: "/assets/skills/jira.svg" },
  { name: "MySQL", image: "/assets/skills/mysql.svg" },
  { name: "Figma", image: "/assets/skills/figma.svg" },
  { name: "Android Studio", image: "/assets/skills/androidstudio.svg" },
  { name: "Github", image: "/assets/skills/github.svg" },
  { name: "VS Code", image: "/assets/skills/visualstudiocode.svg" },
  { name: "Postman", image: "/assets/skills/postman.svg" },
];
