name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: var-ad
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=222222,060010,f65020
            dist/github-snake-light.svg?palette=888888,a0a0a0,ffffff

      - name: Move snake into public folder
        run: |
          mkdir -p public
          cp dist/*.svg public/

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/
          git commit -m "update snake svg" || echo "No changes to commit"
          git push
